services:
  app:
    build: .
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - .:/var/www/html
      - ./etc/caddy/Caddyfile:/etc/frankenphp/Caddyfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVER_NAME: ":80"
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: ${DATABASE_URL}

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5

